const ACTIONS = {
    GET_USER: Symbol('GET_USER'),
    CHANGE_TITLE: Symbol('CHANGE_TITLE'),
    GET_PRODUCTS: Symbol('GET_PRODUCTS'),
    GET_PRODUCTS_SUCCESS: Symbol('GET_PRODUCTS_SUCCESS'),
    SEARCH_PRODUCTS: Symbol('SEARCH_PRODUCTS'),
    FILTER_PRODUCTS: Symbol('FILTER_PRODUCTS'),
    RESET: Symbol('RESET'),
    GET_PRODUCT: Symbol('GET_PRODUCT'),
    GET_PRODUCT_SUCCESS: Symbol('GET_PRODUCT_SUCCESS'),
    ADD_PRODUCT: Symbol('ADD_PRODUCT'),
    ADD_PRODUCT_SUCCESS: Symbol('ADD_PRODUCT_SUCCESS'),
    GET_ORDERED_PRODUCTS: Symbol('GET_ORDERED_PRODUCTS'),
    GET_ORDERED_PRODUCTS_SUCCESS: Symbol('GET_ORDERED_PRODUCTS_SUCCESS'),
    SELECT_VALUE: Symbol('SELECT_VALUE'),
    SAVE_ORDER: Symbol('SAVE_ORDER'),
    SAVE_ORDER_SUCCESS: Symbol('SAVE_ORDER_SUCCESS')
}

export default ACTIONS;