const ACTIONS = {
    GET_USER: Symbol('GET_USER'),
    CHANGE_TITLE: Symbol('CHANGE_TITLE'),
    GET_PRODUCTS: Symbol('GET_PRODUCTS'),
    GET_PRODUCTS_SUCCESS: Symbol('GET_PRODUCTS_SUCCESS'),
    SEARCH_PRODUCTS: Symbol('SEARCH_PRODUCTS'),
    FILTER_PRODUCTS: Symbol('FILTER_PRODUCTS'),
    RESET: Symbol('RESET'),
    GET_PRODUCT: Symbol('GET_PRODUCT'),
    GET_PRODUCT_SUCCESS: Symbol('GET_PRODUCT_SUCCESS'),
    ADD_PRODUCT: Symbol('ADD_PRODUCT'),
    ADD_PRODUCT_SUCCESS: Symbol('ADD_PRODUCT_SUCCESS')    
}

export default ACTIONS;